name: Train ML Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Dagger
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | sh
          sudo mv ./bin/dagger /usr/local/bin/dagger

      - name: Run training pipeline
        run: dagger run go run ./go/pipeline.go

      - name: Rename model
        run: cp artifacts/lead_model_lr.pkl artifacts/model.pkl

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: artifacts/model.pkl
